# @name get-prompts

GET http://localhost:3333/prompts

###

# @name  upload

POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebkitFormBoundaryTeste

------WebkitFormBoundaryTeste
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

./example.mp3
------WebkitFormBoundaryTeste--

###

# @name create-transcription

POST http://localhost:3333/videos/aae82f1f-2244-4431-ac17-723726287b6b/transcription
Content-Type: application/json

{
  "prompt": "vidro do fogao quebrado, concertado, vidro errado"
}
