# @name get-prompts

GET http://localhost:3333/prompts

###

# @name  upload

POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebkitFormBoundaryTeste

------WebkitFormBoundaryTeste
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

./example.mp3
------WebkitFormBoundaryTeste--

###

# @name create-transcription

POST http://localhost:3333/videos/fa60abc1-f317-4f4b-86f3-44f67bec37a5/transcription
Content-Type: application/json

{
  "prompt": "fogão, concertado, vidro errado"
}